version: "1"

services:
  web:
    image: michaelpescelbl/fastapiwithnginx:latest
    env_file: ./app/internal/.env
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - BACKEND_URL=${BACKEND_URL}
      - LOCATION=${LOCATION}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_NAME=${DB_NAME}
      - DB_FULL_CONNECTION=${DB_FULL_CONNECTION}
      - PROJECT_ID=${PROJECT_ID}
      - STORAGE_SERVICE_KEY=${STORAGE_SERVICE_KEY}
      - STORAGE_BUCKET_NAME=${STORAGE_BUCKET_NAME}
      - token_uri=${token_uri}
      - client_id=${client_id}
      - client_secret=${client_secret}
    container_name: web
    ports:
      - "8001:8001"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "100k"

  # app:
  #   build: .
  #   ports:
  #     - "8001:8001"
  
  nginx:
    restart: unless-stopped
    image: nginx
    container_name: nginx
    ports:
      # - "80:80" 
      - "443:443"
    environment:
      - CERTBOT_EMAIL=mpesce@lbl.gov
    volumes:
      - ./nginx:/etc/nginx/user_conf.d:ro
      - /etc/letsencrypt/:/etc/letsencrypt
    depends_on:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"