
name: Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    # -l: login shell, needed when using Conda
    shell: bash -l {0}

env:
  PYTEST_ADDOPTS: "--color=yes"
  PIP_PROGRESS_BAR: "off"

jobs:

  code-formatting:
    name: Check code is formatted (Black)
    # OS and/or Python version don't make a difference, so we choose ubuntu and 3.12 as defaults
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Black
        run: |
          black_requirement="$(grep '^black==' requirements-dev.txt)"
          pip --no-cache-dir install "$black_requirement"
      - name: Run Black to verify that the committed code is formatted
        run: |
          black --check .

#   pylint:
#     name: Code linting (pylint)
#     runs-on: ubuntu-latest
#     needs: [code-formatting]
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-python@v4
#         with:
#           python-version: '3.8'
#       - name: Install dev dependencies
#         run: |
#           pip install -r requirements-dev.txt
#           pip list
#       - name: Run pylint
#         run: |
#           pylint watertap